### ISSUE TITLE
[BUG] Faces not detected

### ISSUE THREAD

**Issue by amirian** [JadHADDAD92/covid-mask-detector#4]
Good Job with high accuracy for single person, but the accuracy lowers down for videos on the internet. I tested it with the video of Trump and his partners wearing masks. It detects very few faces and only in few frames. You can see the result [Here](https://gofile.io/d/3EgEvy). I also used a high resolution version of the video but nothing changed. What is the problem and how to resolve?

**Comment by JadHADDAD92** [comment]
Can you give me the link of the original video (preferably the high-res version),
This is happening due to the confidence threshold of the face detector.
By default, it's 0.6, meaning it discards all the faces that have a confidence level lower than 60%
https://github.com/JadHADDAD92/covid-mask-detector/blob/13879ce513681173f515ce9fd3bcf99803d023ec/covid-mask-detector/common/facedetector.py#L18-L19

you can change that value and lower the threshold level according to your needs when initializing the FaceDetector object 
https://github.com/JadHADDAD92/covid-mask-detector/blob/13879ce513681173f515ce9fd3bcf99803d023ec/covid-mask-detector/video.py#L34-L37

**Comment by amirian** [comment]
Sure, [this](https://gofile.io/d/qbYUzV) is the original video.but I don't think changing the threshold would be a global solution. I studied the code and found that all images are resized to a fixed weight and height. This may cause the problem. By cropping the original video to include only one person, the accuracy is raised. But another problem is with blur images. I checked [this](https://gofile.io/d/ziGszz) image where the face of Trump is detected but that of the background blur face is not. I cropped that face to avoid multi face conflict but that single person is still not detected.
